---
title: "Centro de Transbordo"
author: "SSTYT"
date: "16/3/2017"
output: html_document
---
```{r param, include=FALSE}
#Nombre de la tabla del shape del CTB
shp <- "informacion_geografica.caba"

#Nombre de la tabla de movimientos y gps
gps_mov <- "gps_mov.a2016_05_4"

#Nombre de la geom del shape
geom_shp <- "geom"

#Nombre de la geom de la tabla de movimientos y gps
geom_gps_mov <- "geom_ant"

#Día inicio del analisis
dia_init <- 4

#Dia final del análisis
dia_fin <- 4

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("RPostgreSQL")
library("knitr")
library("dplyr")
library("ggplot2")
library("sqldf")
```

```{r postgres conn, include=FALSE}
# pw <- {
#   "postgres"
# }
# 
# # # loads the PostgreSQL driver
# # drv <- dbDriver("PostgreSQL")
# # # creates a connection to the postgres database
# # note that "con" will be used later in each connection to the database
# con <- dbConnect(
#   drv,
#   dbname = "sube",
#   host = "10.78.10.215",
#   port = 5432,
#   user = "postgres",
#   password = pw
# )

options(sqldf.RPostgreSQL.user = "postgres",
        sqldf.RPostgreSQL.password = "123456",
        sqldf.RPostgreSQL.dbname = "sube",
        sqldf.RPostgreSQL.host = "10.78.10.215",
        sqldf.RPostgreSQL.port = 5432)
```

```{r extraccion, include= FALSE}
base <- sqldf(paste("SELECT nro_tarjeta, codigo_contrato, saldo, categoria, modo, desc_linea, interno ,nro_viaje, etapa_viaje, d, h, velocity_anterior, velocity_siguiente, a.geom_ant FROM", gps_mov," a,", shp, "b",
                     "WHERE a.d BETWEEN", dia_init, "AND", dia_fin,
                     "AND diferencia_tiempo_anterior <= 10 OR diferencia_tiempo_siguiente <= 10 AND a.geom_ant && b.geom AND ST_DISTANCE(a.geom_ant,b.geom) = 0 ;"), drv = "PostgreSQL")
```

```{r queries_string, include=FALSE}

# Cantidad de transacciones, cantidad de transacciones en subte, en colectivo y tren
# query1 <- paste("SELECT COUNT(1) AS trx_total,
# SUM(CASE WHEN modo = 'TREN' THEN 1 ELSE 0 END) AS trx_tren,
# SUM(CASE WHEN modo = 'SUBTE' THEN 1 ELSE 0 END) AS trx_subte,
# SUM(CASE WHEN modo = 'BUS' THEN 1 ELSE 0 END) AS trx_bus
# FROM ", gps_mov," a, ", shp, " b
# WHERE 
# a.geom_ant && b.geom
# AND
# ST_DISTANCE(a.geom_ant,b.geom) = 0;", sep = '')

q1 <- count(base, modo) 
  
# Cantidad de transbordos, cantidad de transbordos en subte, en colectivo y en tren
# query2 <- paste("SELECT COUNT(1) AS tb_total,
# SUM(CASE WHEN modo = 'TREN' THEN 1 ELSE 0 END) AS tb_tren,
# SUM(CASE WHEN modo = 'SUBTE' THEN 1 ELSE 0 END) AS tb_subte,
# SUM(CASE WHEN modo = 'BUS' THEN 1 ELSE 0 END) AS tb_bus
# FROM ", gps_mov," a, ", shp, " b
# WHERE 
# etapa_viaje > 1 
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0;", sep = '')

q2 <- filter(base, base$etapa_viaje > 1) %>% count(., modo)

# TRX por hora
# query3 <- paste("SELECT COUNT(1) AS trx_total,
# SUM(CASE WHEN modo = 'TREN' THEN 1 ELSE 0 END) AS trx_tren,
# SUM(CASE WHEN modo = 'SUBTE' THEN 1 ELSE 0 END) AS trx_subte,
# SUM(CASE WHEN modo = 'BUS' THEN 1 ELSE 0 END) AS trx_bus, h as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# group by h;", sep = '')

q3 <- count(base, modo, h) 
  
# TB por hora
# query4 <- paste("SELECT COUNT(1) AS trx_total,
# SUM(CASE WHEN modo = 'TREN' THEN 1 ELSE 0 END) AS trx_tren,
# SUM(CASE WHEN modo = 'SUBTE' THEN 1 ELSE 0 END) AS trx_subte,
# SUM(CASE WHEN modo = 'BUS' THEN 1 ELSE 0 END) AS trx_bus, h as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# etapa_viaje > 1
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY h;
# ", sep = '')

q4 <- filter(base, base$etapa_viaje > 1) %>% count(., modo, h) 
  
# TRX por linea
# query5 <- paste("SELECT COUNT(1) AS trx_total, desc_linea
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# modo = 'BUS'
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY desc_linea;", sep = '')

q5 <- count(filter(base, base$modo == "BUS"), desc_linea)

# TRX por hora, bus
# query6 <- paste("SELECT COUNT(1) AS trx_total, date_part('h', fecha_trx) as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# modo = 'BUS'
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY date_part('h', fecha_trx);", sep = '')

q6 <- count(filter(base, base$modo == "BUS"), h)

# TRX por hora, tren
# query7 <- paste("SELECT COUNT(1) AS trx_total, date_part('h', fecha_trx) as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# modo = 'TREN'
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY date_part('h', fecha_trx);", sep = '')

q7 <- count(filter(base, base$modo == "TREN"), h)

# TRX por hora, subte
# query8 <- paste("SELECT COUNT(1) AS trx_total, date_part('h', fecha_trx) as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# modo = 'SUBTE'
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY date_part('h', fecha_trx);", sep = '')

q8 <- count(filter(base, base$modo == "SUBTE"), h)

# velocidad por hora
# query9 <- paste("SELECT AVG(a.velocity_anterior) AS velocidad, date_part('h', fecha_trx) as hora
# FROM ", gps_mov," a, ", shp, " b
# WHERE
# modo = 'BUS'
# AND 
# a.geom && b.geom
# AND
# ST_DISTANCE(a.geom,b.geom) = 0
# GROUP BY date_part('h', fecha_trx);", sep = '')

q9 <- summarise(group_by(filter(base, base$modo == "BUS"), h), mean(velocity_anterior))

```

```{r queries_ejecucion, include=FALSE}
#q1 <- dbGetQuery(con, query1)
#q2 <- dbGetQuery(con, query2)
#q3 <- dbGetQuery(con, query3)
#q4 <- dbGetQuery(con, query4)

```
## R Markdown
```{r tablas, echo= FALSE}
#q1
kable(q1, col.names = c("Modo", "Transacciones"), align = 'lc')


```


## Gráficos
```{r graficos, echo= FALSE}
#q1


```


