---
title: "Liquidación Boleto Estudiantil: Subterráneos"
author: "SSTYTRA"
date:
output: pdf_document
---

```{r setup, include=FALSE}
library("RODBC")
library("sqldf")
library("dplyr")
library("knitr")
options(sqldf.RPostgreSQL.user ="postgres",
        sqldf.RPostgreSQL.password ="123456",
        sqldf.RPostgreSQL.dbname ="sube",
        sqldf.RPostgreSQL.host = "10.78.14.54",
        sqldf.RPostgreSQL.port =5432)

```
```{r extraccion, include=FALSE}
# Genero la variables de mes y año para el informe
y <- as.numeric(format(Sys.Date(), "%Y"))
# m <- as.numeric(strftime(as.Date(format(Sys.Date(), "%Y-%m-01")) -1, "%m"))
m <- as.numeric(strftime(as.Date(format(Sys.Date(), "%Y-%m-01")), "%m"))
M <- format(Sys.Date()-30, "%B")

# Tomo los datos del mes correspondiente de la base de datos de NSSA
consulta_nssa <- paste("SELECT * FROM boleto_estudiantil.liquidacion_be_03test WHERE mes_liqui =", m, "AND ano_liqui =", y)
reporte_be_nssa <- sqldf(consulta_nssa, drv = "PostgreSQL")

# Tomo los datos de empresa_linea_ramal actualizados
elr <- sqldf("SELECT * FROM tablas_complementarias.empresa_linea_ramal", drv = "PostgreSQL")

length(unique(reporte_be_nssa$id_linea)) ==  length(unique(elr[elr$id_linea %in% reporte_be_nssa$id_linea,"id_linea"]))

# Creo la tabla reporte enriquecida con los datos de empresa_linea_ramal

reporte_be <- left_join(x = reporte_be_nssa, y = elr, by = "id_linea")

# Genero la tabla base de trabajo, agrupa por empresa y linea y suma la cantidad de usos

reporte_be_sum <- group_by(reporte_be, id_empresa, desc_empresa, id_linea, desc_linea) %>% summarise(.,sum(cantidad_usos))

# Filtro para generar una tabla que presente sólo los datos del subte

reporte_be_subte1 <- filter(reporte_be_sum, id_empresa == 1)

reporte_be_subte <- reporte_be_subte1[ , -c(grep("id_empresa", colnames(reporte_be_subte1)), grep("id_linea", colnames(reporte_be_subte1)))]

# Función para calcular el monto a transferir por los usos (queda pendiente que se defina esta regla de liquidación)

calc_monto <- function(usos, tarifa) {
  resultado = usos * tarifa
  return(resultado)
}

# Genero la columna de monto en la tabla

reporte_be_subte$monto <- calc_monto(reporte_be_subte$`sum(cantidad_usos)`, 5) 
```
El presente reporte corresponde a liquidación a subterráneos en concepto del boleto estudiantil durante el mes de `r M` del año `r y`. En el siguiente cuadro se presenta el detalle de la asignación de montos.


```{r a, echo=FALSE} 
#Tabla de liquidación para subte
kable(reporte_be_subte, col.names = c("Empresa", "Línea", "Usos", "Monto"), align = 'llrr')
```